import type { Word } from "./types";

type Entry = Omit<Word, "id" | "source">;

const entries: Entry[] = [
  { word: "Hallo", translation: "hello / hi", example: "Hallo! Wie geht's?", exampleTranslation: "Hi! How's it going?" },
  { word: "Tschüss", translation: "bye", example: "Tschüss, bis morgen!", exampleTranslation: "Bye, see you tomorrow!" },
  { word: "Danke", translation: "thank you", example: "Danke schön!", exampleTranslation: "Thank you very much!" },
  { word: "Bitte", translation: "please / you're welcome", example: "Einen Kaffee, bitte.", exampleTranslation: "A coffee, please." },
  { word: "Ja", translation: "yes", example: "Ja, gern.", exampleTranslation: "Yes, gladly." },
  { word: "Nein", translation: "no", example: "Nein, danke.", exampleTranslation: "No, thank you." },
  { word: "Guten Morgen", translation: "good morning", example: "Guten Morgen! Wie geht es Ihnen?", exampleTranslation: "Good morning! How are you? (formal)" },
  { word: "Gute Nacht", translation: "good night", example: "Gute Nacht, schlaf gut!", exampleTranslation: "Good night, sleep well!" },
  { word: "Entschuldigung", translation: "excuse me / sorry", example: "Entschuldigung, wo ist die Toilette?", exampleTranslation: "Excuse me, where is the restroom?" },
  { word: "Ich heiße…", translation: "my name is…", example: "Ich heiße Zac.", exampleTranslation: "My name is Zac." },
  { word: "Wie geht's?", translation: "how are you?", example: "Hallo Anna, wie geht's?", exampleTranslation: "Hi Anna, how are you?" },
  { word: "gut", translation: "good / well", example: "Mir geht's gut, danke.", exampleTranslation: "I'm doing well, thanks." },
  { word: "das Wasser", translation: "water", example: "Ein Glas Wasser, bitte.", exampleTranslation: "A glass of water, please.", note: "das = neuter noun." },
  { word: "das Essen", translation: "food / meal", example: "Das Essen ist lecker.", exampleTranslation: "The food is delicious." },
  { word: "der Kaffee", translation: "coffee", example: "Ich trinke gern Kaffee.", exampleTranslation: "I like drinking coffee.", note: "der = masculine noun." },
  { word: "das Brot", translation: "bread", example: "Das Brot ist frisch.", exampleTranslation: "The bread is fresh." },
  { word: "das Haus", translation: "house", example: "Das Haus ist groß.", exampleTranslation: "The house is big." },
  { word: "der Freund / die Freundin", translation: "friend (m / f)", example: "Sie ist meine Freundin.", exampleTranslation: "She is my friend." },
  { word: "die Mutter", translation: "mother", example: "Meine Mutter ist zu Hause.", exampleTranslation: "My mother is at home.", note: "die = feminine noun." },
  { word: "der Vater", translation: "father", example: "Mein Vater arbeitet.", exampleTranslation: "My father is working.", note: "The V sounds like an F." },
  { word: "die Katze", translation: "cat", example: "Die Katze schläft.", exampleTranslation: "The cat is sleeping." },
  { word: "der Hund", translation: "dog", example: "Ich habe einen Hund.", exampleTranslation: "I have a dog." },
  { word: "das Buch", translation: "book", example: "Das ist ein gutes Buch.", exampleTranslation: "That is a good book." },
  { word: "eins", translation: "one", example: "Eins, zwei, drei!", exampleTranslation: "One, two, three!" },
  { word: "zwei", translation: "two", example: "Zwei Kaffee, bitte.", exampleTranslation: "Two coffees, please." },
  { word: "drei", translation: "three", example: "Ich habe drei Brüder.", exampleTranslation: "I have three brothers." },
  { word: "ich", translation: "I", example: "Ich bin Student.", exampleTranslation: "I am a student." },
  { word: "du", translation: "you (informal)", example: "Sprichst du Englisch?", exampleTranslation: "Do you speak English?" },
  { word: "essen", translation: "to eat", example: "Ich möchte essen.", exampleTranslation: "I would like to eat." },
  { word: "trinken", translation: "to drink", example: "Ich trinke Wasser.", exampleTranslation: "I drink water." },
  { word: "sprechen", translation: "to speak", example: "Ich spreche ein bisschen Deutsch.", exampleTranslation: "I speak a little German." },
  { word: "ich möchte", translation: "I would like", example: "Ich möchte einen Tee.", exampleTranslation: "I would like a tea." },
  { word: "groß", translation: "big / tall", example: "Berlin ist groß.", exampleTranslation: "Berlin is big.", note: "ß sounds like a sharp s." },
  { word: "klein", translation: "small", example: "Mein Hund ist klein.", exampleTranslation: "My dog is small." },
  { word: "heute", translation: "today", example: "Heute ist es kalt.", exampleTranslation: "It's cold today." },
  { word: "morgen", translation: "tomorrow", example: "Bis morgen!", exampleTranslation: "See you tomorrow!" },
  { word: "wo?", translation: "where?", example: "Wo ist der Bahnhof?", exampleTranslation: "Where is the train station?" },
  { word: "was?", translation: "what?", example: "Was ist das?", exampleTranslation: "What is that?" },
  { word: "die Toilette", translation: "restroom / toilet", example: "Wo ist die Toilette?", exampleTranslation: "Where is the restroom?" },
  { word: "die Rechnung", translation: "the bill / check", example: "Die Rechnung, bitte.", exampleTranslation: "The check, please." },
  // --- More words ---
  { word: "vier", translation: "four", example: "Das macht vier Euro.", exampleTranslation: "That's four euros." },
  { word: "fünf", translation: "five", example: "Ich habe fünf Minuten.", exampleTranslation: "I have five minutes." },
  { word: "sechs", translation: "six", example: "Es ist sechs Uhr.", exampleTranslation: "It's six o'clock." },
  { word: "sieben", translation: "seven", example: "Die Woche hat sieben Tage.", exampleTranslation: "The week has seven days." },
  { word: "acht", translation: "eight", example: "Der Kurs beginnt um acht.", exampleTranslation: "The class starts at eight." },
  { word: "neun", translation: "nine", example: "Der Laden öffnet um neun.", exampleTranslation: "The shop opens at nine." },
  { word: "zehn", translation: "ten", example: "Das kostet zehn Euro.", exampleTranslation: "That costs ten euros." },
  { word: "rot", translation: "red", example: "Mein Auto ist rot.", exampleTranslation: "My car is red." },
  { word: "blau", translation: "blue", example: "Der Himmel ist blau.", exampleTranslation: "The sky is blue." },
  { word: "grün", translation: "green", example: "Ich trinke grünen Tee.", exampleTranslation: "I drink green tea." },
  { word: "weiß", translation: "white", example: "Das Haus ist weiß.", exampleTranslation: "The house is white." },
  { word: "schwarz", translation: "black", example: "Ich trinke Kaffee schwarz.", exampleTranslation: "I drink my coffee black." },
  { word: "der Bruder", translation: "brother", example: "Mein Bruder ist Student.", exampleTranslation: "My brother is a student." },
  { word: "die Schwester", translation: "sister", example: "Ich habe eine Schwester.", exampleTranslation: "I have a sister." },
  { word: "der Tee", translation: "tea", example: "Einen Tee, bitte.", exampleTranslation: "A tea, please." },
  { word: "die Milch", translation: "milk", example: "Kaffee mit Milch, bitte.", exampleTranslation: "Coffee with milk, please." },
  { word: "der Käse", translation: "cheese", example: "Ich mag Käse.", exampleTranslation: "I like cheese." },
  { word: "der Apfel", translation: "apple", example: "Ich esse einen Apfel.", exampleTranslation: "I'm eating an apple." },
  { word: "die Straße", translation: "street", example: "Wo ist diese Straße?", exampleTranslation: "Where is this street?" },
  { word: "die Stadt", translation: "city / town", example: "Berlin ist eine große Stadt.", exampleTranslation: "Berlin is a big city." },
  { word: "ich habe", translation: "I have", example: "Ich habe eine Katze.", exampleTranslation: "I have a cat.", note: "From haben (to have)." },
  { word: "ich brauche", translation: "I need", example: "Ich brauche Wasser.", exampleTranslation: "I need water.", note: "From brauchen (to need)." },
  { word: "ich mag", translation: "I like", example: "Ich mag diese Stadt.", exampleTranslation: "I like this city." },
  { word: "Was kostet das?", translation: "how much is it?", example: "Entschuldigung, was kostet das?", exampleTranslation: "Excuse me, how much is it?" },
  { word: "rechts", translation: "right", example: "Dann rechts.", exampleTranslation: "Then right." },
  { word: "links", translation: "left", example: "Die Toilette ist links.", exampleTranslation: "The restroom is on the left." },
  { word: "geradeaus", translation: "straight ahead", example: "Gehen Sie geradeaus.", exampleTranslation: "Go straight ahead." },
  { word: "gern geschehen", translation: "you're welcome", example: "Danke! — Gern geschehen.", exampleTranslation: "Thanks! — You're welcome." },
  { word: "Es tut mir leid", translation: "I'm sorry", example: "Es tut mir leid, ich habe keine Zeit.", exampleTranslation: "I'm sorry, I don't have time." },
  { word: "Ich verstehe nicht", translation: "I don't understand", example: "Entschuldigung, ich verstehe nicht.", exampleTranslation: "Sorry, I don't understand." },
];

export const GERMAN_STARTER: Word[] = entries.map((e, i) => ({
  ...e,
  id: `de-starter-${i}`,
  source: "starter",
}));
