import type { Word } from "./types";

type Entry = Omit<Word, "id" | "source">;

const entries: Entry[] = [
  { word: "hola", translation: "hello / hi", example: "¡Hola! ¿Cómo estás?", exampleTranslation: "Hi! How are you?", note: "The h is silent: OH-la." },
  { word: "adiós", translation: "goodbye", example: "Adiós, ¡hasta mañana!", exampleTranslation: "Goodbye, see you tomorrow!" },
  { word: "gracias", translation: "thank you", example: "Muchas gracias.", exampleTranslation: "Thank you very much." },
  { word: "por favor", translation: "please", example: "Un café, por favor.", exampleTranslation: "A coffee, please." },
  { word: "sí", translation: "yes", example: "Sí, quiero agua.", exampleTranslation: "Yes, I want water.", note: "With an accent it means yes; without (si) it means if." },
  { word: "no", translation: "no / not", example: "No, gracias.", exampleTranslation: "No, thank you." },
  { word: "buenos días", translation: "good morning", example: "Buenos días, señora.", exampleTranslation: "Good morning, ma'am." },
  { word: "buenas noches", translation: "good evening / good night", example: "Buenas noches, hasta mañana.", exampleTranslation: "Good night, see you tomorrow." },
  { word: "perdón", translation: "sorry / excuse me", example: "Perdón, ¿dónde está el baño?", exampleTranslation: "Excuse me, where is the bathroom?" },
  { word: "me llamo…", translation: "my name is…", example: "Me llamo Zac.", exampleTranslation: "My name is Zac." },
  { word: "¿cómo estás?", translation: "how are you?", example: "Hola, ¿cómo estás?", exampleTranslation: "Hi, how are you?" },
  { word: "bien", translation: "well / fine / good", example: "Estoy bien, gracias.", exampleTranslation: "I'm fine, thanks." },
  { word: "mucho gusto", translation: "nice to meet you", example: "Me llamo Ana. ¡Mucho gusto!", exampleTranslation: "My name is Ana. Nice to meet you!" },
  { word: "el agua", translation: "water", example: "Quiero agua, por favor.", exampleTranslation: "I want water, please.", note: "Feminine, but uses \"el\" because it starts with a stressed a." },
  { word: "la comida", translation: "food / meal", example: "La comida está muy rica.", exampleTranslation: "The food is very tasty." },
  { word: "el café", translation: "coffee / café", example: "Me gusta el café.", exampleTranslation: "I like coffee." },
  { word: "el pan", translation: "bread", example: "El pan está en la mesa.", exampleTranslation: "The bread is on the table." },
  { word: "la casa", translation: "house / home", example: "Mi casa es pequeña.", exampleTranslation: "My house is small." },
  { word: "el amigo / la amiga", translation: "friend (m / f)", example: "Ella es mi amiga.", exampleTranslation: "She is my friend." },
  { word: "la familia", translation: "family", example: "Mi familia es grande.", exampleTranslation: "My family is big." },
  { word: "el gato", translation: "cat", example: "El gato duerme.", exampleTranslation: "The cat is sleeping." },
  { word: "el perro", translation: "dog", example: "Tengo un perro.", exampleTranslation: "I have a dog.", note: "Roll the double rr!" },
  { word: "el libro", translation: "book", example: "Es un buen libro.", exampleTranslation: "It's a good book." },
  { word: "uno", translation: "one", example: "Un café, por favor.", exampleTranslation: "One coffee, please.", note: "Becomes \"un\" before a masculine noun." },
  { word: "dos", translation: "two", example: "Dos cervezas, por favor.", exampleTranslation: "Two beers, please." },
  { word: "tres", translation: "three", example: "Tengo tres hermanos.", exampleTranslation: "I have three siblings." },
  { word: "yo", translation: "I", example: "Yo soy estudiante.", exampleTranslation: "I am a student." },
  { word: "tú", translation: "you (informal)", example: "¿Tú hablas inglés?", exampleTranslation: "Do you speak English?" },
  { word: "comer", translation: "to eat", example: "Quiero comer.", exampleTranslation: "I want to eat." },
  { word: "beber", translation: "to drink", example: "Quiero beber agua.", exampleTranslation: "I want to drink water." },
  { word: "hablar", translation: "to speak", example: "Hablo un poco de español.", exampleTranslation: "I speak a little Spanish." },
  { word: "quiero", translation: "I want", example: "Quiero un café.", exampleTranslation: "I want a coffee.", note: "From querer (to want)." },
  { word: "grande", translation: "big", example: "Es una ciudad grande.", exampleTranslation: "It's a big city." },
  { word: "pequeño", translation: "small", example: "Tengo un perro pequeño.", exampleTranslation: "I have a small dog." },
  { word: "hoy", translation: "today", example: "Hoy hace sol.", exampleTranslation: "It's sunny today." },
  { word: "mañana", translation: "tomorrow / morning", example: "¡Hasta mañana!", exampleTranslation: "See you tomorrow!" },
  { word: "¿dónde?", translation: "where?", example: "¿Dónde está el metro?", exampleTranslation: "Where is the metro?" },
  { word: "¿qué?", translation: "what?", example: "¿Qué es esto?", exampleTranslation: "What is this?" },
  { word: "el baño", translation: "bathroom / restroom", example: "¿Dónde está el baño?", exampleTranslation: "Where is the bathroom?" },
  { word: "la cuenta", translation: "the bill / check", example: "La cuenta, por favor.", exampleTranslation: "The check, please." },
  // --- More words ---
  { word: "cuatro", translation: "four", example: "Son cuatro euros.", exampleTranslation: "That's four euros." },
  { word: "cinco", translation: "five", example: "Tengo cinco minutos.", exampleTranslation: "I have five minutes." },
  { word: "seis", translation: "six", example: "Son las seis.", exampleTranslation: "It's six o'clock." },
  { word: "siete", translation: "seven", example: "La semana tiene siete días.", exampleTranslation: "The week has seven days." },
  { word: "ocho", translation: "eight", example: "La clase es a las ocho.", exampleTranslation: "The class is at eight." },
  { word: "nueve", translation: "nine", example: "La tienda abre a las nueve.", exampleTranslation: "The shop opens at nine." },
  { word: "diez", translation: "ten", example: "Cuesta diez euros.", exampleTranslation: "It costs ten euros." },
  { word: "rojo", translation: "red", example: "Mi coche es rojo.", exampleTranslation: "My car is red.", note: "Becomes roja for feminine nouns." },
  { word: "azul", translation: "blue", example: "El cielo es azul.", exampleTranslation: "The sky is blue." },
  { word: "verde", translation: "green", example: "Me gusta el té verde.", exampleTranslation: "I like green tea." },
  { word: "blanco", translation: "white", example: "La casa es blanca.", exampleTranslation: "The house is white." },
  { word: "negro", translation: "black", example: "Quiero un café negro.", exampleTranslation: "I want a black coffee." },
  { word: "la madre", translation: "mother", example: "Mi madre está en casa.", exampleTranslation: "My mother is at home." },
  { word: "el padre", translation: "father", example: "Mi padre trabaja mucho.", exampleTranslation: "My father works a lot." },
  { word: "el hermano / la hermana", translation: "brother / sister", example: "Tengo una hermana.", exampleTranslation: "I have a sister." },
  { word: "la leche", translation: "milk", example: "Un café con leche, por favor.", exampleTranslation: "A coffee with milk, please." },
  { word: "el queso", translation: "cheese", example: "Me gusta el queso.", exampleTranslation: "I like cheese." },
  { word: "la manzana", translation: "apple", example: "Como una manzana.", exampleTranslation: "I'm eating an apple." },
  { word: "la calle", translation: "street", example: "¿Dónde está esta calle?", exampleTranslation: "Where is this street?" },
  { word: "la ciudad", translation: "city", example: "Madrid es una ciudad grande.", exampleTranslation: "Madrid is a big city." },
  { word: "tengo", translation: "I have", example: "Tengo un gato.", exampleTranslation: "I have a cat.", note: "From tener (to have)." },
  { word: "necesito", translation: "I need", example: "Necesito agua.", exampleTranslation: "I need water.", note: "From necesitar (to need)." },
  { word: "me gusta", translation: "I like", example: "Me gusta esta ciudad.", exampleTranslation: "I like this city." },
  { word: "¿cuánto cuesta?", translation: "how much is it?", example: "¿Cuánto cuesta el café?", exampleTranslation: "How much is the coffee?" },
  { word: "a la derecha", translation: "to the right", example: "El baño está a la derecha.", exampleTranslation: "The bathroom is on the right." },
  { word: "a la izquierda", translation: "to the left", example: "Gire a la izquierda.", exampleTranslation: "Turn left." },
  { word: "todo recto", translation: "straight ahead", example: "Siga todo recto.", exampleTranslation: "Go straight ahead." },
  { word: "de nada", translation: "you're welcome", example: "¡Gracias! — De nada.", exampleTranslation: "Thanks! — You're welcome." },
  { word: "lo siento", translation: "I'm sorry", example: "Lo siento, no tengo tiempo.", exampleTranslation: "I'm sorry, I don't have time." },
  { word: "no entiendo", translation: "I don't understand", example: "Perdón, no entiendo.", exampleTranslation: "Sorry, I don't understand." },
];

export const SPANISH_STARTER: Word[] = entries.map((e, i) => ({
  ...e,
  id: `es-starter-${i}`,
  source: "starter",
}));
