import type { Word } from "./types";

type Entry = Omit<Word, "id" | "source">;

// Stress is marked with an acute accent (е́). Native texts don't show it,
// but it's a big help while learning.
const entries: Entry[] = [
  { word: "приве́т", translation: "hi (informal)", example: "Приве́т! Как дела́?", exampleTranslation: "Hi! How are you?" },
  { word: "здра́вствуйте", translation: "hello (formal)", example: "Здра́вствуйте! Меня́ зову́т А́нна.", exampleTranslation: "Hello! My name is Anna.", translit: "zdrástvuyte", note: "The first в is silent." },
  { word: "пока́", translation: "bye", example: "Пока́, до за́втра!", exampleTranslation: "Bye, see you tomorrow!" },
  { word: "спаси́бо", translation: "thank you", example: "Спаси́бо большо́е!", exampleTranslation: "Thank you very much!" },
  { word: "пожа́луйста", translation: "please / you're welcome", example: "Ко́фе, пожа́луйста.", exampleTranslation: "Coffee, please.", translit: "pozháluysta" },
  { word: "да", translation: "yes", example: "Да, я хочу́ чай.", exampleTranslation: "Yes, I want tea." },
  { word: "нет", translation: "no", example: "Нет, спаси́бо.", exampleTranslation: "No, thank you.", translit: "nyet" },
  { word: "извини́те", translation: "excuse me / sorry", example: "Извини́те, где туале́т?", exampleTranslation: "Excuse me, where is the restroom?" },
  { word: "меня́ зову́т…", translation: "my name is…", example: "Меня́ зову́т Зак.", exampleTranslation: "My name is Zac.", note: "Literally \"they call me…\"." },
  { word: "как дела́?", translation: "how are you?", example: "Приве́т, как дела́?", exampleTranslation: "Hi, how are you?" },
  { word: "хорошо́", translation: "good / well / OK", example: "Всё хорошо́.", exampleTranslation: "Everything is fine.", translit: "kharashó", note: "Unstressed о sounds like \"a\"." },
  { word: "вода́", translation: "water", example: "Я пью во́ду.", exampleTranslation: "I drink water.", translit: "vadá" },
  { word: "еда́", translation: "food", example: "Еда́ о́чень вку́сная.", exampleTranslation: "The food is very tasty." },
  { word: "чай", translation: "tea", example: "Я люблю́ чай.", exampleTranslation: "I love tea." },
  { word: "ко́фе", translation: "coffee", example: "Я пью ко́фе у́тром.", exampleTranslation: "I drink coffee in the morning." },
  { word: "хлеб", translation: "bread", example: "Хлеб на столе́.", exampleTranslation: "The bread is on the table.", translit: "khlep" },
  { word: "дом", translation: "house / home", example: "Мой дом большо́й.", exampleTranslation: "My house is big." },
  { word: "друг", translation: "friend", example: "Он мой друг.", exampleTranslation: "He is my friend.", translit: "druk" },
  { word: "ма́ма", translation: "mom", example: "Ма́ма до́ма.", exampleTranslation: "Mom is at home." },
  { word: "па́па", translation: "dad", example: "Па́па рабо́тает.", exampleTranslation: "Dad is working." },
  { word: "ко́шка", translation: "cat", example: "Ко́шка спит.", exampleTranslation: "The cat is sleeping." },
  { word: "соба́ка", translation: "dog", example: "У меня́ есть соба́ка.", exampleTranslation: "I have a dog.", translit: "sabáka" },
  { word: "кни́га", translation: "book", example: "Э́то хоро́шая кни́га.", exampleTranslation: "This is a good book." },
  { word: "оди́н", translation: "one", example: "Оди́н ко́фе, пожа́луйста.", exampleTranslation: "One coffee, please.", translit: "adín" },
  { word: "два", translation: "two", example: "Два ча́я, пожа́луйста.", exampleTranslation: "Two teas, please." },
  { word: "три", translation: "three", example: "У меня́ три кни́ги.", exampleTranslation: "I have three books." },
  { word: "я", translation: "I", example: "Я студе́нт.", exampleTranslation: "I am a student." },
  { word: "ты", translation: "you (informal)", example: "Ты говори́шь по-англи́йски?", exampleTranslation: "Do you speak English?" },
  { word: "есть", translation: "to eat", example: "Я хочу́ есть.", exampleTranslation: "I'm hungry. (I want to eat.)", note: "Also means \"there is / to have\" in у меня́ есть." },
  { word: "пить", translation: "to drink", example: "Я хочу́ пить.", exampleTranslation: "I'm thirsty. (I want to drink.)" },
  { word: "говори́ть", translation: "to speak", example: "Я говорю́ по-англи́йски.", exampleTranslation: "I speak English." },
  { word: "я хочу́", translation: "I want", example: "Я хочу́ ко́фе.", exampleTranslation: "I want coffee." },
  { word: "большо́й", translation: "big", example: "Э́то большо́й го́род.", exampleTranslation: "This is a big city.", translit: "bal'shóy" },
  { word: "ма́ленький", translation: "small", example: "У меня́ ма́ленькая ко́шка.", exampleTranslation: "I have a small cat.", note: "Ending changes with gender: -ий (m), -ая (f), -ое (n)." },
  { word: "сего́дня", translation: "today", example: "Сего́дня хоро́шая пого́да.", exampleTranslation: "The weather is nice today.", translit: "sivódnya", note: "The г is pronounced like a v." },
  { word: "за́втра", translation: "tomorrow", example: "До за́втра!", exampleTranslation: "See you tomorrow!" },
  { word: "где?", translation: "where?", example: "Где метро́?", exampleTranslation: "Where is the metro?" },
  { word: "что?", translation: "what?", example: "Что э́то?", exampleTranslation: "What is this?", translit: "shto" },
  { word: "туале́т", translation: "restroom / toilet", example: "Где туале́т?", exampleTranslation: "Where is the restroom?" },
  { word: "счёт", translation: "the bill / check", example: "Счёт, пожа́луйста.", exampleTranslation: "The check, please.", translit: "shchyot" },
  // --- More words ---
  { word: "четы́ре", translation: "four", example: "У меня́ четы́ре кни́ги.", exampleTranslation: "I have four books.", translit: "chetýre" },
  { word: "пять", translation: "five", example: "Пять мину́т, пожа́луйста.", exampleTranslation: "Five minutes, please." },
  { word: "шесть", translation: "six", example: "Сейча́с шесть часо́в.", exampleTranslation: "It's six o'clock now." },
  { word: "семь", translation: "seven", example: "В неде́ле семь дней.", exampleTranslation: "There are seven days in a week." },
  { word: "во́семь", translation: "eight", example: "Уро́к в во́семь.", exampleTranslation: "The lesson is at eight." },
  { word: "де́вять", translation: "nine", example: "Магази́н открыва́ется в де́вять.", exampleTranslation: "The shop opens at nine." },
  { word: "де́сять", translation: "ten", example: "Э́то сто́ит де́сять е́вро.", exampleTranslation: "This costs ten euros." },
  { word: "кра́сный", translation: "red", example: "Мой люби́мый цвет — кра́сный.", exampleTranslation: "My favorite color is red." },
  { word: "си́ний", translation: "blue", example: "Не́бо си́нее.", exampleTranslation: "The sky is blue.", note: "Ending changes with gender: си́ний, си́няя, си́нее." },
  { word: "зелёный", translation: "green", example: "Я пью зелёный чай.", exampleTranslation: "I drink green tea.", note: "ё is always stressed." },
  { word: "бе́лый", translation: "white", example: "Э́то бе́лый дом.", exampleTranslation: "This is a white house." },
  { word: "чёрный", translation: "black", example: "Я люблю́ чёрный ко́фе.", exampleTranslation: "I love black coffee." },
  { word: "брат", translation: "brother", example: "Мой брат студе́нт.", exampleTranslation: "My brother is a student." },
  { word: "сестра́", translation: "sister", example: "Моя́ сестра́ до́ма.", exampleTranslation: "My sister is at home." },
  { word: "молоко́", translation: "milk", example: "Ко́фе с молоко́м, пожа́луйста.", exampleTranslation: "Coffee with milk, please.", translit: "malakó" },
  { word: "сыр", translation: "cheese", example: "Я люблю́ сыр.", exampleTranslation: "I love cheese." },
  { word: "я́блоко", translation: "apple", example: "Я ем я́блоко.", exampleTranslation: "I'm eating an apple." },
  { word: "у́лица", translation: "street", example: "Где э́та у́лица?", exampleTranslation: "Where is this street?" },
  { word: "го́род", translation: "city / town", example: "Москва́ — большо́й го́род.", exampleTranslation: "Moscow is a big city.", translit: "górat" },
  { word: "у меня́ есть", translation: "I have", example: "У меня́ есть брат.", exampleTranslation: "I have a brother.", translit: "u menyá yest'", note: "Literally \"by me there is\"." },
  { word: "мне ну́жно", translation: "I need to", example: "Мне ну́жно идти́.", exampleTranslation: "I need to go." },
  { word: "мне нра́вится", translation: "I like", example: "Мне нра́вится э́тот го́род.", exampleTranslation: "I like this city." },
  { word: "ско́лько сто́ит?", translation: "how much is it?", example: "Ско́лько сто́ит ко́фе?", exampleTranslation: "How much is the coffee?" },
  { word: "напра́во", translation: "to the right", example: "Пото́м напра́во.", exampleTranslation: "Then to the right." },
  { word: "нале́во", translation: "to the left", example: "Туале́т нале́во.", exampleTranslation: "The restroom is on the left." },
  { word: "пря́мо", translation: "straight ahead", example: "Иди́те пря́мо.", exampleTranslation: "Go straight ahead." },
  { word: "не́ за что", translation: "you're welcome", example: "Спаси́бо! — Не́ за что.", exampleTranslation: "Thanks! — You're welcome.", translit: "nyé za shto" },
  { word: "здесь", translation: "here", example: "Метро́ здесь.", exampleTranslation: "The metro is here.", translit: "zdes'" },
  { word: "там", translation: "there", example: "Банк там.", exampleTranslation: "The bank is over there." },
  { word: "я не понима́ю", translation: "I don't understand", example: "Извини́те, я не понима́ю.", exampleTranslation: "Sorry, I don't understand." },
];

export const RUSSIAN_STARTER: Word[] = entries.map((e, i) => ({
  ...e,
  id: `ru-starter-${i}`,
  source: "starter",
}));
